spring:
  profiles:
    active: ide  # 기본 활성화 프로필 (IDE 환경)


---
spring:
  config:
    activate:
      on-profile: ide

  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true

server:
  port: 8080
# 파일 업로드 경로 설정
upload:
  path: D:/boot/images

---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://mysql:3306/community?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true

server:
  port: 8080

---
# 공통 설정
spring:
  application:
    name: community

  jackson:
    time-zone: Asia/Seoul

  datasource:
    hikari:
      minimum-idle: 10
      maximum-pool-size: 12
      idle-timeout: 300000
     # max-lifetime: 1740000

  server:
    tomcat:
      threads:
        max: 30
        min-spare: 30
      max-connections: 2000
      accept-count: 200
