spring:
  application:
    name: community

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: jdbc:mysql://localhost:3306/community?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      minimum-idle: 5              # 최소 유휴 커넥션 수 감소
      maximum-pool-size: 16        # CPU 코어 기반으로 최대 풀 크기 조정 (4 × 2~3)
      idle-timeout: 300000         # 유휴 시간 유지 (5분)
      max-lifetime: 1800000        # 최대 수명 유지 (30분)
      connection-timeout: 10000    # 커넥션 타임아웃 단축 (10초)


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect   # 최신 Hibernate Dialect 사용 (Hibernate 6.x)
    show-sql: true                                  # SQL 쿼리 출력 활성화
    properties:
      hibernate:
        generate_statistics: true                   # Hibernate 통계 활성화
        cache:
          use_second_level_cache: true              # Hibernate 2차 캐시 활성화
          use_query_cache: true                     # 쿼리 캐시 활성화 (선택 사항)
        region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory # JCache 사용
      javax:
        cache:
          provider: org.ehcache.jsr107.EhcacheCachingProvider # Ehcache 사용

  cache:
    jcache:
      config: classpath:ehcache.xml                 # Ehcache 설정 파일 경로 지정